name: 'YAML Substitute'
description: 'Replace a k8s yaml deployment with the '
inputs:
  env-file:  
    description: 'Additional variables to set'
    default: ''
  yaml-file:  
    description: 'The yaml file to substitute'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/substitute.sh -y ${{inputs.yaml-file}} -f ${{inputs.env-file}}
      if: ${{inputs.env-file != ''}}
    - run: ${{ github.action_path }}/substitute.sh -y ${{inputs.yaml-file}}
      if: ${{inputs.env-file == ''}}
